general_configs:
  seed: 0


# data source configs:
download_configs:
  download_chunk_size: 128
  github_metdata_url: https://github.com/WayScience/targeted_fibrosis_drug_screen/archive/refs/heads/main.zip


# this contains the configs used for mAP
compound_ap_configs:
  pos_sameby: ["Metadata_broad_sample"]
  pos_diffby: []
  neg_sameby: []
  neg_diffby: ["Metadata_broad_sample", "Metadata_treatment_index"]
  batch_size: 20000
  distance: cosine

compound_map_configs:
  pos_sameby: ["Metadata_broad_sample"]
  neg_diffby: ["Metadata_broad_sample", "Metadata_treatment_index"]
  batch_size: 20000
  distance: cosine





# these configs is part of analysis two were select metadata columns were we aim to evaluate
# the MOA of each compound
moa_ap_configs:
  pos_sameby: ["Metadata_broad_sample"]
  pos_diffby: []
  neg_sameby: []
  neg_diffby: ["Metadata_broad_sample", "Metadata_treatment_index"]
  batch_size: 20000
  distance: cosine

compound_map_configs:
    pos_sameby: []
    null_size: 10000
    threshold: 0.05
