general_configs:
  seed: 0 

# this contains the configs used for mAP  
compound_ap_configs: 
  pos_sameby: ["Metadata_broad_sample"]
  pos_diffby: []
  neg_sameby: []
  neg_diffby: ["Metadata_broad_sample", "Metadata_treatment_index"]
  batch_size: 20000
  distance: cosine

# these configs is part of analysis two were select metadata columns were we aim to evaluate 
# the MOA of each compound 
moa_ap_configs:
  pos_sameby: ["Metadata_broad_sample"]
  pos_diffby: []
  neg_sameby: []
  neg_diffby: ["Metadata_broad_sample", "Metadata_treatment_index"]
  batch_size: 20000
  distance: cosine

compound_map_configs: 
    pos_sameby: []
    null_size: 10000
    threshold: 0.05

